site_name: Moje projekty
site_author: Justyna Lasecka
site_description: >-
    Portfolio moich projektów z Data Science i AI-+

repo_name: justynalasecka/ds_ai_portfolio
repo_url: https://github.com/justynalasecka/ds_ai_portfolio.git

theme:
  name: material
  palette:
    primary: deep purple

nav:
- Strona Domowa: index.md
- Projekty:
  - "Ankieta": ankieta/index.md
  - "Biegacz": biegacz/index.md
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md
  - "Wykrywacz najważniejszej zmiennej wpływającej na wynik": wykrywacz_najwazniejszej_zmiennej/index.md

markdown_extensions: 
  - attr_list
  - md_in_html